# Generated by Django 5.0.5 on 2025-06-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_cdh97_index_preface"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="publish_date",
            field=models.DateField(
                blank=True,
                help_text="Publish date to display for this post. Leave blank to use the date the post was first published.",
                null=True,
                verbose_name="Publish Date",
            ),
        ),
    ]
