# Generated by Django 5.0.5 on 2025-06-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0026_blogpost_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglandingpage",
            name="featured_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.blogpost",
            ),
        ),
    ]
