- name: Make a directory for virtualenv
  file:
      path: "{{ deploy }}/env"
      state: directory
      mode: "u+rwx,g+rwx,o-rw"
- name: Upgrade pip to latest in virtualenv
  pip:
    name: pip
    state: latest
    virtualenv: "{{ deploy }}/env"
    virtualenv_site_packages: yes
- name: Set perms
  file:
      path: "{{ deploy }}/env"
      state: directory
      mode: "u+rwx,g+rwx,o-rw"
- name: Install requirements via pip (MySQLdb should be system version and skipped)
  pip:
    virtualenv: "{{ deploy }}/env"
    requirements: "{{ deploy }}/requirements.txt"
    virtualenv_site_packages: yes
- name: Install local_settings.py
  synchronize:
    src: /home/deploy/{{ djangoapp }}/local_settings.py
    dest: "{{ deploy }}/{{ djangoapp }}/local_settings.py"
  delegate_to: '{{ inventory_hostname }}'
- name: Run ./manage.py collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ deploy }}"
    virtualenv: "{{ deploy }}/env"
- name: Configure CACHE for django-compressor
  file:
    path: '{{ deploy }}/static/CACHE'
    state: directory
    owner: deploy
    group: apache
    mode: 0770
