version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
  minHeight: 1024
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
static:
  baseUrl: /
  files: "**/*.{html,htm}"
  ignore: ""
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
