language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cp ci/testsettings.py cdhWebsite/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> cdhWebsite/local_settings.py

script:
  - py.test --cov=./

after_success:
- codecov
