language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - gem install sass
  - cp ci/testsettings.py cdhweb/local_settings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> cdhweb/local_settings.py

script:
  - py.test --cov=cdhweb

after_success:
- codecov
