# Generated by Django 2.2.17 on 2021-01-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_personlistpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateListPage',
            fields=[
                ('personlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.PersonListPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('people.personlistpage',),
        ),
        migrations.CreateModel(
            name='ExecListPage',
            fields=[
                ('personlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.PersonListPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('people.personlistpage',),
        ),
        migrations.CreateModel(
            name='SpeakerListPage',
            fields=[
                ('personlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.PersonListPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('people.personlistpage',),
        ),
        migrations.CreateModel(
            name='StaffListPage',
            fields=[
                ('personlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.PersonListPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('people.personlistpage',),
        ),
        migrations.CreateModel(
            name='StudentListPage',
            fields=[
                ('personlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.PersonListPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('people.personlistpage',),
        ),
    ]
