# Generated by Django 5.0.5 on 2025-06-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0025_alter_peoplecategorypage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="positions",
            field=models.ManyToManyField(
                blank=True, through="people.Position", to="people.person"
            ),
        ),
    ]
